TheBloke_Yi-34B-Chat-GPTQ$:
  loader: Transformers
  cpu_memory: 0
  auto_devices: true
  disk: false
  cpu: false
  bf16: false
  load_in_8bit: false
  trust_remote_code: true
  no_use_fast: false
  use_flash_attention_2: false
  load_in_4bit: false
  compute_dtype: float16
  quant_type: nf4
  use_double_quant: false
  disable_exllama: false
  disable_exllamav2: false
  compress_pos_emb: 1
  alpha_value: 1
  rope_freq_base: 5000000
  gpu_memory_0: 22000
  gpu_memory_1: 22000
TheBloke_Mixtral-8x7B-Instruct-v0.1-GPTQ_gptq-4bit-32g-actorder_True$:
  loader: Transformers
  cpu_memory: 0
  auto_devices: true
  disk: false
  cpu: false
  bf16: false
  load_in_8bit: false
  trust_remote_code: true
  no_use_fast: false
  use_flash_attention_2: false
  load_in_4bit: false
  compute_dtype: float16
  quant_type: nf4
  use_double_quant: false
  disable_exllama: false
  disable_exllamav2: false
  compress_pos_emb: 1
  alpha_value: 1
  rope_freq_base: 1000000
  gpu_memory_0: 22000
  gpu_memory_1: 22000
